# Day-3 Assignment 2

In [1]:
import numpy as np

In [2]:
list1=[]
list2=[]
n1=0
n2=0
 
while n1<5:
    num1=int(input())
    list1.append(num1)
    n1 +=1
print(" ")
while n2<5:
    num2=int(input())
    list2.append(num2)
    n2 +=1
 
#converting list1 and list2 to np array
arr1=np.asarray(list1)
arr2=np.asarray(list2)
 
#concenating arr1 and arr2
arr=np.asarray([arr1,arr2])
print(arr)
 
#sorting arr
sort_arr=np.sort(arr)
print(sort_arr)

12
34
23
46
54
 
12
32
44
11
28
[[12 34 23 46 54]
 [12 32 44 11 28]]
[[12 23 34 46 54]
 [11 12 28 32 44]]
